### PR TITLE
Show deps in task listing under help message

### PR DESCRIPTION
**Pull request by JiDai**

### CODE REVIEW

**Comment by chmontgomery** [comment]
Thanks, I like the idea! A couple things:

1. Can you add tests?
1. What do you think about putting the task dep list on the same line as the message? Putting it on a new line seems to clutter up the messaging. e.g.
   *  `ci       Run all CI verification [lint]`
1. Can we change the color from dark blue to cyan? I think that would visually make it more obvious that it represents a task. Also, the dark blue is hard to read against a typical black background

**Comment by JiDai** [comment]
Ok, I tried to write tests but I don't know the tool and I did not understand how to do :) I will spend more time to understand later today or this week-end. 
Other points will be done : 
- My dark blue is not so dark in my theme :)
- For the new line, I made this because my shell is pretty narrow.

I suppose a template option should be good for new lines and color problems. Maybe I will do that.

**Comment by chmontgomery** [comment]
I like the updates! I agree, having options for colors would be ideal in case of different shell themes.

As far as tests, they're all in `test.js`, written in [mocha](http://mochajs.org/) and run via `gulp test`. Hopefully you can follow what's already there and do something similar?...

**Comment by JiDai** [comment]
Yep, that's what I did but in a test you wrote, the dep array property on task object (in attach-help.js) is never defined, so the depsMessage is always empty. And I don't understand why...
The test : 
```
    it('with help text and deps', function () {
      gulp.task('newStyle', 'help text here', ['dep'], gutil.noop);
      should(originalTaskFn.callCount).eql(3);
      should(originalTaskFn.calledWith('newStyle', ['dep'], gutil.noop)).ok;
      should(gulp.tasks.newStyle.help).ok;

      console.log(gulp.tasks.newStyle.help.depsMessage); // Always empty

      should(gulp.tasks.newStyle.help.message).eql('help text here');
    });
```

**Comment by JiDai** [comment]
I add test but I must modify the code to do it. Tell me if we can do better.

**Comment by chmontgomery** [comment]
:+1: looks great!

**Comment by chmontgomery** [comment]
landed in `v1.4.0`

**Comment by JiDai** [comment]
OK thanks :)

**Pull request merged**
